### ISSUE TITLE
Menu Page

### ISSUE THREAD

**Issue by HeathJHMoore** [HeathJHMoore/PizzaUI#2]
As a user, when I am on the Menu Page, I should be able to browse through items categorized into three categories:

- Pizza
- Sides
- Drinks

When I click on each of these category buttons, I should be able to see a scrollable window with all of the items in this category. When I click "Add to Order" on any of the items, I should see the item show up on the right side of the page in the "My Order" section.

Finally, when I am done building my order, I should be able to Click "Submit Order" and it save my order to the database.

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/109397121-ba702180-78fa-11eb-93e0-39558b3127f3.png)

**Comment by ItaiKumengisa** [comment]
I think I'm done with this. For the part where it says 'Click "Submit Order" and it save my order to the database' I just had it send the order to the console. I figured I'd handle that part when I'm doing the API integration
